version: "3.7"

services:
  backend:
    build: .
    ports: 
      - 8080:8080
    restart: unless-stopped

#  postgres:
#    image: postgres:13
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_PASSWORD: app
#      POSTGRES_USER: app
#      POSTGRES_DB: db

#volumes:
#  postgres-data:
