POST http://localhost:8080/company
Content-Type: application/json

{
  "email": "string",
  "password": "string",
  "website": "string",
  "address": "string",
  "name": "string"
}
###

GET http://localhost:8080/company

###

GET http://localhost:8080/company/1
