POST http://localhost:8080/company
Content-Type: application/json

{
  "password": "12345",
  "email": "office@infilmity.at",
  "website": "infilmity.at",
  "name": "Infilmity",
  "address": "Limesstraße 12-14",
  "employees": null,
  "admins": null
}
###

GET http://localhost:8080/company
