POST http://localhost:8080/vacancy
Content-Type: application/json

{
  "company": {
    "id": 1
  },
  "deadline": "2021-12-31",
  "opened": true,
  "project": {
    "id": 1
  },
  "title": "string"
}
###

GET http://localhost:8080/vacancy

###

GET http://localhost:8080/vacancy/60

###

GET http://localhost:8080/vacancy/1/applicants

###

POST http://localhost:8080/vacancy/1/applicants?personId=1
